<a href="https://colab.research.google.com/github/Fet-elena/proba/blob/main/NLP2_homework_Fetisova_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NLP2_1
https://www.hackerrank.com/challenges/detect-the-email-addresses/problem?isFullScreen=true

r'\w+[\w\.]*\w+@\w+[\w\.]*\w+'

NLP2_2 https://www.hackerrank.com/challenges/detect-the-domain-name/problem?isFullScreen=true

r'(?<=://)[A-Za-z0-9-\.]+\.[A-Za-z]+'

In [75]:
 !pip install pymorphy2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 62.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=39f0ef6bd9abdf80772d7669340db9ab039f9b49dc2c9726810686dae652ede8
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt


In [110]:
import pandas as pd
import numpy as np

from numpy import dot
from numpy.linalg import norm
import pandas as pd
import nltk
from nltk.tokenize import WordPunctTokenizer
from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
from pymorphy2 import MorphAnalyzer
nltk.download("wordnet", "whatever_the_absolute_path_to_myapp_is/nltk_data/")
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to
[nltk_data]     whatever_the_absolute_path_to_myapp_is/nltk_data/...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

NLP2_3 (дз1): Реализовать stemming, lemmatization & BoW на следующем датасете: https://cloud.mail.ru/public/Z4L3/vB8GcgTtK (Russian Toxic-abuse comments)

In [114]:
labeled = pd.read_csv("labeled.csv")
labeled

comment  toxic
0                   Верблюдов-то за что? Дебилы, бл...\n    1.0
1      Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                              Собаке - собачья смерть\n    1.0
3      Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4      тебя не убедил 6-страничный пдф в том, что Скр...    1.0
...                                                  ...    ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...    1.0
14408  А кого любить? Гоблина тупорылого что-ли? Или ...    1.0
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...    0.0
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...    1.0
14411  До сих пор пересматриваю его видео. Орамбо кст...    0.0

[14412 rows x 2 columns]

In [115]:
from typing_extensions import dataclass_transform
comment=[]
for i in labeled.comment:
  comment.append(i)
comment[:10]

['Верблюдов-то за что? Дебилы, бл...\n',
 'Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.\n',
 'Собаке - собачья смерть\n',
 'Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?\n',
 'тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)\n',
 'Для каких стан является эталоном современная система здравоохранения РФ? Для Зимбабве? Ты тупой? хохлы\n',
 'В шапке были ссылки на инфу по текущему фильму марвел. Эти ссылки были заменены на фразу Репортим брипидора, игнорируем его посты. Если этого недостаточно, чтобы понять, что модератор абсолютный неадекват, и его нужно лишить полномочий, тогда эта борда пробивает абсолютное дно по неадекватности.\n',
 'УПАД Т! ТАМ НЕЛЬЗЯ СТРОИТЬ! ТЕХНОЛОГИЙ НЕТ! РАЗВОРУЮТ КАК ВСЕГДА! УЖЕ ТР

In [90]:
tokenizer = WordPunctTokenizer()
data_tok = []
for i in comment:
  data_tok.append(tokenizer.tokenize(i.lower()))
data_tok[:1]

[['верблюдов', '-', 'то', 'за', 'что', '?', 'дебилы', ',', 'бл', '...']]

In [82]:
import warnings
warnings.filterwarnings("ignore")

def vectorize(tokens):
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector

def unique(sequence):
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]

nltk.download('stopwords')
stop_words = set(stopwords.words('russian'))
special_char=[",",":"," ",";",".","?"]

snowball = SnowballStemmer(language="russian")
morph = MorphAnalyzer()

data_tok_lem_stem = []
for i in data_tok:
    string = []
    for j in i:
        word = snowball.stem(morph.normal_forms(j)[0])
        string.append(word)
    data_tok_lem_stem.append(string)

lem_stem_words = []
for i in data_tok_lem_stem:
  for j in i:
    lem_stem_words.append(j)

vocab=unique(lem_stem_words)

filtered_vocab=[]
for w in vocab:
    if w not in stop_words and w not in special_char:
        filtered_vocab.append(w)

vector = []
for i in data_tok_lem_stem:
    vector.append(vectorize(i))
print('Количество уникальных слов:',len(vocab))
print('Количество уникальных слов без мусора:',len(filtered_vocab))
print('Количество векторов:',len(vector))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Количество уникальных слов: 30890
Количество уникальных слов без мусора: 30813
Количество векторов: 14412


NLP2_4 Реализовать классификатор токсичных комментариев tfidf на базе датасета
https://www.kaggle.com/datasets/blackmoon/russian-language-toxic-comments  

Дубликат файла: https://cloud.mail.ru/public/Z4L3/vB8GcgTtK



In [118]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(lem_stem_words)
feature_names = tfidf_vectorizer.get_feature_names_out()
tfidf_scores = tfidf_matrix.toarray()[0]
sorted_keywords = [word for _, word in sorted(zip(tfidf_scores, feature_names), reverse=True)]
print(tfidf_matrix)
print("Ключевые слова:", sorted_keywords)


#count = CountVectorizer(ngram_range = (1,3))
# count = CountVectorizer(ngram_range = (1,1))
#word_count=count.fit_transform(text,)
#print(word_count)


  (0, 4982)	1.0
  (2, 26860)	1.0
  (3, 9138)	1.0
  (4, 29668)	1.0
  (6, 7561)	1.0
  (8, 4073)	1.0
  (10, 29083)	1.0
  (12, 30463)	1.0
  (13, 17610)	1.0
  (14, 9875)	1.0
  (15, 23598)	1.0
  (17, 14405)	1.0
  (19, 5635)	1.0
  (23, 29039)	1.0
  (24, 8910)	1.0
  (25, 19300)	1.0
  (27, 8890)	1.0
  (28, 4615)	1.0
  (29, 29039)	1.0
  (30, 15469)	1.0
  (31, 4660)	1.0
  (33, 11492)	1.0
  (34, 17193)	1.0
  (35, 4615)	1.0
  (36, 21255)	1.0
  :	:
  (486475, 24212)	1.0
  (486476, 11056)	1.0
  (486477, 19079)	1.0
  (486478, 20754)	1.0
  (486479, 12030)	1.0
  (486481, 16228)	1.0
  (486482, 11286)	1.0
  (486483, 19300)	1.0
  (486485, 26475)	1.0
  (486486, 8943)	1.0
  (486488, 30093)	1.0
  (486489, 15469)	1.0
  (486490, 23184)	1.0
  (486491, 24135)	1.0
  (486493, 29093)	1.0
  (486494, 29124)	1.0
  (486495, 14909)	1.0
  (486496, 29668)	1.0
  (486497, 11686)	1.0
  (486499, 26860)	1.0
  (486500, 17193)	1.0
  (486501, 4998)	1.0
  (486503, 26447)	1.0
  (486504, 6935)	1.0
  (486505, 4902)	1.0
Ключевые слова:

In [117]:
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
